services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agents
    ports:
      - "5433:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      # - pg_data:/var/lib/postgresql/data
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - PORT=3000
#     volumes:
#       - .:/app
#     command: ["npm", "run", "start"]
#     depends_on:
#       - nlw-agents-pg

# volumes:
#   db_data:
#     driver: local
